# Generated by Django 3.2.8 on 2021-11-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.EmailField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
