# Generated by Django 3.2.8 on 2021-11-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
